## Import Libraries

In [2]:
# Import Polars for dataframe analytics
import polars as pl
# Improt Path to manage file paths
from pathlib import Path

## Define Data Path

In [3]:
# Define data folder path
data_folder = Path("../data")

## Load Cleaned Dataset

In [4]:
# Load cleaned sales dataset
sales_df = pl.read_parquet(data_folder / "sales_cleaned.parquet")

# Preview Dataset
sales_df.head()

shape: (5, 13)
┌────────────────┬─────────────┬────────────┬─────────────────┬───┬─────┬────────┬───────┬─────────┐
│ transaction_id ┆ customer_id ┆ product_id ┆ purchase_date   ┆ … ┆ age ┆ gender ┆ price ┆ revenue │
│ ---            ┆ ---         ┆ ---        ┆ ---             ┆   ┆ --- ┆ ---    ┆ ---   ┆ ---     │
│ str            ┆ str         ┆ str        ┆ datetime[μs]    ┆   ┆ i64 ┆ str    ┆ i64   ┆ i64     │
╞════════════════╪═════════════╪════════════╪═════════════════╪═══╪═════╪════════╪═══════╪═════════╡
│ T82            ┆ c377        ┆ p3         ┆ 2024-01-01      ┆ … ┆ 21  ┆ Female ┆ 149   ┆ 149     │
│                ┆             ┆            ┆ 00:00:00        ┆   ┆     ┆        ┆       ┆         │
│ T910           ┆ c202        ┆ p1         ┆ 2024-01-01      ┆ … ┆ 51  ┆ Male   ┆ 499   ┆ 499     │
│                ┆             ┆            ┆ 00:00:00        ┆   ┆     ┆        ┆       ┆         │
│ T1273          ┆ c752        ┆ p2         ┆ 2024-01-01      ┆ … ┆ 48  ┆ Male   ┆ 199   ┆ 199     │
│                ┆             ┆            ┆ 00:00:00        ┆   ┆     ┆        ┆       ┆         │
│ T1369          ┆ c739        ┆ p0         ┆ 2024-01-01      ┆ … ┆ 49  ┆ Female ┆ 299   ┆ 299     │
│                ┆             ┆            ┆ 00:00:00        ┆   ┆     ┆        ┆       ┆         │
│ T2858          ┆ c169        ┆ p1         ┆ 2024-01-01      ┆ … ┆ 51  ┆ Female ┆ 499   ┆ 499     │
│                ┆             ┆            ┆ 00:00:00        ┆   ┆     ┆        ┆       ┆         │
└────────────────┴─────────────┴────────────┴─────────────────┴───┴─────┴────────┴───────┴─────────┘

## Create Customer-Level Metrics

In [5]:
# Aggregate customer level behavior
customer_metrics = (sales_df.group_by("customer_id").agg(

    # Total orders per customer
    pl.len().alias("total_orders"),

    # Total money spent
    pl.col("revenue").sum().alias("total_spent"),

    # Average order value
    pl.col("revenue").mean().alias("avg_order_value"),

    # First Purchase date
    pl.col("purchase_date").min().alias("first_purchase"),

    # Last purchase date
    pl.col("purchase_date").max().alias("last_purchase")

)
)
customer_metrics.head()

shape: (5, 6)
┌─────────────┬──────────────┬─────────────┬─────────────────┬─────────────────────┬───────────────┐
│ customer_id ┆ total_orders ┆ total_spent ┆ avg_order_value ┆ first_purchase      ┆ last_purchase │
│ ---         ┆ ---          ┆ ---         ┆ ---             ┆ ---                 ┆ ---           │
│ str         ┆ u32          ┆ i64         ┆ f64             ┆ datetime[μs]        ┆ datetime[μs]  │
╞═════════════╪══════════════╪═════════════╪═════════════════╪═════════════════════╪═══════════════╡
│ c970        ┆ 50           ┆ 16850       ┆ 337.0           ┆ 2024-01-01 00:00:00 ┆ 2024-12-10    │
│             ┆              ┆             ┆                 ┆                     ┆ 00:00:00      │
│ c935        ┆ 73           ┆ 23277       ┆ 318.863014      ┆ 2024-01-05 00:00:00 ┆ 2024-12-31    │
│             ┆              ┆             ┆                 ┆                     ┆ 00:00:00      │
│ c486        ┆ 48           ┆ 15652       ┆ 326.083333      ┆ 2024-01-11 00:00:00 ┆ 2024-11-28    │
│             ┆              ┆             ┆                 ┆                     ┆ 00:00:00      │
│ c589        ┆ 69           ┆ 21231       ┆ 307.695652      ┆ 2024-01-11 00:00:00 ┆ 2024-12-30    │
│             ┆              ┆             ┆                 ┆                     ┆ 00:00:00      │
│ c717        ┆ 48           ┆ 15052       ┆ 313.583333      ┆ 2024-01-03 00:00:00 ┆ 2024-12-20    │
│             ┆              ┆             ┆                 ┆                     ┆ 00:00:00      │
└─────────────┴──────────────┴─────────────┴─────────────────┴─────────────────────┴───────────────┘

## Calculate Customer Lifetime

In [6]:
# Calculate customer lifetime in days
customer_metrics = customer_metrics.with_columns(
    (pl.col("last_purchase") - pl.col("first_purchase")
     ).dt.total_days().alias("customer_lifetime_days")
)

customer_metrics.tail(10)

shape: (10, 7)
┌─────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ customer_id ┆ total_orders ┆ total_spent ┆ avg_order_v ┆ first_purch ┆ last_purcha ┆ customer_li │
│ ---         ┆ ---          ┆ ---         ┆ alue        ┆ ase         ┆ se          ┆ fetime_days │
│ str         ┆ u32          ┆ i64         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│             ┆              ┆             ┆ f64         ┆ datetime[μs ┆ datetime[μs ┆ i64         │
│             ┆              ┆             ┆             ┆ ]           ┆ ]           ┆             │
╞═════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ c249        ┆ 47           ┆ 15153       ┆ 322.404255  ┆ 2024-01-21  ┆ 2024-12-10  ┆ 324         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c810        ┆ 48           ┆ 16502       ┆ 343.791667  ┆ 2024-01-05  ┆ 2024-12-25  ┆ 355         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c308        ┆ 11           ┆ 3389        ┆ 308.090909  ┆ 2024-01-27  ┆ 2024-10-27  ┆ 274         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c338        ┆ 55           ┆ 17595       ┆ 319.909091  ┆ 2024-01-01  ┆ 2024-12-27  ┆ 361         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c797        ┆ 43           ┆ 13707       ┆ 318.767442  ┆ 2024-01-06  ┆ 2024-12-31  ┆ 360         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c475        ┆ 59           ┆ 21291       ┆ 360.864407  ┆ 2024-01-08  ┆ 2024-12-31  ┆ 358         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c374        ┆ 96           ┆ 33154       ┆ 345.354167  ┆ 2024-01-06  ┆ 2024-12-27  ┆ 356         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c704        ┆ 38           ┆ 14012       ┆ 368.736842  ┆ 2024-01-04  ┆ 2024-12-29  ┆ 360         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c741        ┆ 42           ┆ 13858       ┆ 329.952381  ┆ 2024-01-20  ┆ 2024-12-31  ┆ 346         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
│ c172        ┆ 25           ┆ 8175        ┆ 327.0       ┆ 2024-01-15  ┆ 2024-12-28  ┆ 348         │
│             ┆              ┆             ┆             ┆ 00:00:00    ┆ 00:00:00    ┆             │
└─────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

## Calculate Purchase Frequency

In [7]:
# Purchase frequecy = orders / lifetime
customer_metrics = customer_metrics.with_columns(
    (
        pl.col("total_orders") / (pl.col("customer_lifetime_days")+1
                                  )
    ).alias("purchase_frequency")
)

# Note:- adding +1 avoids divide by 0 for single purchase customer
customer_metrics.head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ total_orde ┆ total_spen ┆ avg_order ┆ first_pur ┆ last_purc ┆ customer_ ┆ purchase_ │
│ d          ┆ rs         ┆ t          ┆ _value    ┆ chase     ┆ hase      ┆ lifetime_ ┆ frequency │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ days      ┆ ---       │
│ str        ┆ u32        ┆ i64        ┆ f64       ┆ datetime[ ┆ datetime[ ┆ ---       ┆ f64       │
│            ┆            ┆            ┆           ┆ μs]       ┆ μs]       ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ c970       ┆ 50         ┆ 16850      ┆ 337.0     ┆ 2024-01-0 ┆ 2024-12-1 ┆ 344       ┆ 0.144928  │
│            ┆            ┆            ┆           ┆ 1         ┆ 0         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c935       ┆ 73         ┆ 23277      ┆ 318.86301 ┆ 2024-01-0 ┆ 2024-12-3 ┆ 361       ┆ 0.201657  │
│            ┆            ┆            ┆ 4         ┆ 5         ┆ 1         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c486       ┆ 48         ┆ 15652      ┆ 326.08333 ┆ 2024-01-1 ┆ 2024-11-2 ┆ 322       ┆ 0.148607  │
│            ┆            ┆            ┆ 3         ┆ 1         ┆ 8         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c589       ┆ 69         ┆ 21231      ┆ 307.69565 ┆ 2024-01-1 ┆ 2024-12-3 ┆ 354       ┆ 0.194366  │
│            ┆            ┆            ┆ 2         ┆ 1         ┆ 0         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c717       ┆ 48         ┆ 15052      ┆ 313.58333 ┆ 2024-01-0 ┆ 2024-12-2 ┆ 352       ┆ 0.135977  │
│            ┆            ┆            ┆ 3         ┆ 3         ┆ 0         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

# Save Customer Level Dataset

This dataset will later power segmentation and churn analysis

In [8]:
# Save customer level metrics
customer_metrics.write_csv(data_folder / "customer_level_metrics.csv")

# Save customer level metrics in parquet
customer_metrics.write_parquet(data_folder / "customer_level_metrics.parquet")

## Calculate Global KPIs

Computing business-level metrics.

In [9]:
# Total customers
total_customers = sales_df.select(
    pl.col("customer_id").n_unique()
).item()

# Total orders
total_orders = sales_df.height

# Total revenue
total_revenue = sales_df.select(
    pl.col("revenue").sum()
).item()

## Calculate Ecommerce Metrics

In [10]:
# Average order value
aov = total_revenue / total_orders

# Purhcase frequency
purchase_frequency = total_orders / total_customers

# Revenue per customer
revenue_per_customer = total_revenue / total_customers

## Repeat Purchase Rate

In [11]:
# Customers with multiple purchases
repeat_customers = customer_metrics.filter(
    pl.col("total_orders") > 1
).height

repeat_purchase_rate = repeat_customers / total_customers

print("Repeat Customer:", repeat_customers)
print("Repeat Purchase Rate:", repeat_purchase_rate)

Repeat Customer: 1000
Repeat Purchase Rate: 1.0

## Create KPI Tables

In [12]:
# Create KPI dataframe
metrics_df = pl.DataFrame(
    {
        "metric": [
            "Total Customers",
            "Total Orders",
            "Total Revenue",
            "Average Order Value",
            "Purchase Frequency",
            "Revenue per Customer",
            "Repeat Customers",
            "Repeat Purchase Rate"
        ],
        "value": [
            float(total_customers),
            float(total_orders),
            float(total_revenue),
            round(aov, 2),
            round(purchase_frequency, 2),
            round(revenue_per_customer, 2),
            round(repeat_customers, 2),
            round(repeat_purchase_rate, 2)
        ]
    }
)

metrics_df

shape: (8, 2)
┌──────────────────────┬────────────┐
│ metric               ┆ value      │
│ ---                  ┆ ---        │
│ str                  ┆ f64        │
╞══════════════════════╪════════════╡
│ Total Customers      ┆ 1000.0     │
│ Total Orders         ┆ 50000.0    │
│ Total Revenue        ┆ 1.624595e7 │
│ Average Order Value  ┆ 324.92     │
│ Purchase Frequency   ┆ 50.0       │
│ Revenue per Customer ┆ 16245.95   │
│ Repeat Customers     ┆ 1000.0     │
│ Repeat Purchase Rate ┆ 1.0        │
└──────────────────────┴────────────┘

In [13]:
metrics_df.sort("value", descending=True)

shape: (8, 2)
┌──────────────────────┬────────────┐
│ metric               ┆ value      │
│ ---                  ┆ ---        │
│ str                  ┆ f64        │
╞══════════════════════╪════════════╡
│ Total Revenue        ┆ 1.624595e7 │
│ Total Orders         ┆ 50000.0    │
│ Revenue per Customer ┆ 16245.95   │
│ Total Customers      ┆ 1000.0     │
│ Repeat Customers     ┆ 1000.0     │
│ Average Order Value  ┆ 324.92     │
│ Purchase Frequency   ┆ 50.0       │
│ Repeat Purchase Rate ┆ 1.0        │
└──────────────────────┴────────────┘

In [14]:
customer_metrics.sort("total_orders", descending=True).head()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ customer_i ┆ total_orde ┆ total_spen ┆ avg_order ┆ first_pur ┆ last_purc ┆ customer_ ┆ purchase_ │
│ d          ┆ rs         ┆ t          ┆ _value    ┆ chase     ┆ hase      ┆ lifetime_ ┆ frequency │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ days      ┆ ---       │
│ str        ┆ u32        ┆ i64        ┆ f64       ┆ datetime[ ┆ datetime[ ┆ ---       ┆ f64       │
│            ┆            ┆            ┆           ┆ μs]       ┆ μs]       ┆ i64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ c102       ┆ 110        ┆ 36590      ┆ 332.63636 ┆ 2024-01-1 ┆ 2024-12-2 ┆ 349       ┆ 0.314286  │
│            ┆            ┆            ┆ 4         ┆ 4         ┆ 8         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c22        ┆ 109        ┆ 35191      ┆ 322.85321 ┆ 2024-01-0 ┆ 2024-12-2 ┆ 357       ┆ 0.304469  │
│            ┆            ┆            ┆ 1         ┆ 4         ┆ 6         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c821       ┆ 104        ┆ 34296      ┆ 329.76923 ┆ 2024-01-0 ┆ 2024-12-3 ┆ 361       ┆ 0.287293  │
│            ┆            ┆            ┆ 1         ┆ 4         ┆ 0         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c860       ┆ 103        ┆ 34947      ┆ 339.29126 ┆ 2024-01-0 ┆ 2024-12-2 ┆ 357       ┆ 0.287709  │
│            ┆            ┆            ┆ 2         ┆ 7         ┆ 9         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
│ c937       ┆ 101        ┆ 32849      ┆ 325.23762 ┆ 2024-01-0 ┆ 2024-12-3 ┆ 365       ┆ 0.275956  │
│            ┆            ┆            ┆ 4         ┆ 1         ┆ 1         ┆           ┆           │
│            ┆            ┆            ┆           ┆ 00:00:00  ┆ 00:00:00  ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [15]:
customer_metrics.describe()

shape: (9, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ customer_ ┆ total_ord ┆ total_spe ┆ … ┆ first_pur ┆ last_purc ┆ customer_ ┆ purchase │
│ ---       ┆ id        ┆ ers       ┆ nt        ┆   ┆ chase     ┆ hase      ┆ lifetime_ ┆ _frequen │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ days      ┆ cy       │
│           ┆ str       ┆ f64       ┆ f64       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1000      ┆ 1000.0    ┆ 1000.0    ┆ … ┆ 1000      ┆ 1000      ┆ 1000.0    ┆ 1000.0   │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 50.0      ┆ 16245.95  ┆ … ┆ 2024-01-1 ┆ 2024-12-2 ┆ 345.395   ┆ 0.143393 │
│           ┆           ┆           ┆           ┆   ┆ 1 07:32:0 ┆ 1 17:00:5 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 9.600000  ┆ 7.600000  ┆           ┆          │
│ std       ┆ null      ┆ 17.516702 ┆ 5803.4582 ┆ … ┆ null      ┆ null      ┆ 17.474162 ┆ 0.047757 │
│           ┆           ┆           ┆ 24        ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ c0        ┆ 7.0       ┆ 2493.0    ┆ … ┆ 2024-01-0 ┆ 2024-10-2 ┆ 205.0     ┆ 0.033981 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆ 3         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆ 00:00:00  ┆           ┆          │
│ 25%       ┆ null      ┆ 38.0      ┆ 12214.0   ┆ … ┆ 2024-01-0 ┆ 2024-12-1 ┆ 339.0     ┆ 0.109145 │
│           ┆           ┆           ┆           ┆   ┆ 3         ┆ 8         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆ 00:00:00  ┆           ┆          │
│ 50%       ┆ null      ┆ 49.0      ┆ 15955.0   ┆ … ┆ 2024-01-0 ┆ 2024-12-2 ┆ 350.0     ┆ 0.142012 │
│           ┆           ┆           ┆           ┆   ┆ 7         ┆ 6         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆ 00:00:00  ┆           ┆          │
│ 75%       ┆ null      ┆ 61.0      ┆ 19691.0   ┆ … ┆ 2024-01-1 ┆ 2024-12-2 ┆ 358.0     ┆ 0.173021 │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆ 9         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆ 00:00:00  ┆           ┆          │
│ max       ┆ c999      ┆ 110.0     ┆ 36590.0   ┆ … ┆ 2024-06-0 ┆ 2024-12-3 ┆ 365.0     ┆ 0.314286 │
│           ┆           ┆           ┆           ┆   ┆ 6         ┆ 1         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ 00:00:00  ┆ 00:00:00  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
customer_metrics.select([
    pl.col("total_orders").min().alias("min_orders"),
    pl.col("total_orders").mean().alias("avg_orders"),
    pl.col("total_orders").max().alias("max_orders")
])

shape: (1, 3)
┌────────────┬────────────┬────────────┐
│ min_orders ┆ avg_orders ┆ max_orders │
│ ---        ┆ ---        ┆ ---        │
│ u32        ┆ f64        ┆ u32        │
╞════════════╪════════════╪════════════╡
│ 7          ┆ 50.0       ┆ 110        │
└────────────┴────────────┴────────────┘

## Save Metrics Dataset

In [17]:
# Save KPI Dataset
metrics_df.write_csv(data_folder / "customer_behavior_metrics.csv")

metrics_df.write_parquet(data_folder / "customer_behavior_metrics.parquet")

# Adding Customer Segmentation

In [36]:
customer_metrics = customer_metrics.with_columns(

    pl.when(pl.col("total_spent") > 30000).then(pl.lit("VIP"))
    .when(pl.col("total_orders") >= 30).then(pl.lit("Loyal"))
    .when(pl.col("total_orders") >= 10).then(pl.lit("Regular"))
    .otherwise(pl.lit("Low Value"))
    .alias("customer_type")

)

In [37]:
customer_metrics.group_by("customer_type").count()

C:\Users\Mudit PC\AppData\Local\Temp\ipykernel_20912\2212270806.py:1: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  customer_metrics.group_by("customer_type").count()

shape: (4, 2)
┌───────────────┬───────┐
│ customer_type ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ Regular       ┆ 111   │
│ Low Value     ┆ 2     │
│ Loyal         ┆ 874   │
│ VIP           ┆ 13    │
└───────────────┴───────┘

In [38]:
sales_encriched = sales_df.join(
    customer_metrics.select(["customer_id", "customer_type"]),
    on="customer_id",
    how="left"
)

In [39]:
sales_encriched.select("customer_type").unique()

shape: (4, 1)
┌───────────────┐
│ customer_type │
│ ---           │
│ str           │
╞═══════════════╡
│ Loyal         │
│ Low Value     │
│ VIP           │
│ Regular       │
└───────────────┘

In [40]:
sales_encriched.write_parquet(data_folder / "sales_encriched.parquet")